### ISSUE TITLE
Unable to assume the service linked role

### ISSUE THREAD

**Issue by fabio-paiva-sp** [aws-samples/run-selenium-tests-at-scale-using-ecs-fargate#2]
Creating the application in a new account I get the following error:

```
Resource handler returned message: "Invalid request provided: CreateCluster Invalid Request: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
```

**Comment by fabio-paiva-sp** [comment]
on a second deployment it worked

**Comment by hariohmprasath** [comment]
Hi @fabiopaiva,

I am just surprised with this error because CDK creates all the required roles with permissions. But I am glad it worked, have fun. Thanks.
